apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: expense
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "expense-ebs"
  resources:
    requests:
      storage: 4Gi
---
#stateful set      
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysql
spec:
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  serviceName: "nginx"
  replicas: 3 
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
      containers:
      - name: mysql
        image: narendranreddy/mysql:v1.0
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql

